---
# This role installs and sets up keepalived

- name: Install keepalived (debian/ubuntu)
  apt: name=keepalived state=present
  when: ansible_os_family == "Debian"
  tags: keepalived
  notify: restart keepalived

- name: Configure keepalived
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=running
  tags: keepalived
