---
- hosts: "*:!repository"
  user: root

  pre_tasks:
    - name: Stop all nodes
      command: "{{ splunk_installation.splunk_home_path }}/bin/splunk stop"
      become_user: splunk
      become_method: su

  roles:
    - { role: upgrade_master, when: "'masternode' in group_names" }
    - { role: upgrade_peers, when: "'masternode' not in group_names" }

  post_tasks:
    - name: Disable maintenance mode
      command: "{{ splunk_installation.splunk_home_path }}/bin/splunk disable maintenance-mode"
      become: true
      become_user: splunk
      become_method: su
      when: "'masternode' in group_names"
