---
- hosts: "*:!repository"
  user: root

  pre_tasks:
    - name: Stop all nodes
      command: "{{ splunk_installation.splunk_home_path }}/bin/splunk stop"
      become_user: splunk
      become_method: su

  roles:
    - upgrade-master
      when: "'masternode' in group_names"
    - upgrade-peers
      when: "'masternode' not in group_names"
