---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [replication_port:<port>]
#####################################################################################################################

# This tasks contains a workaround for a bug in ini_file module (option=dummy)
- name: "Configure server.conf [replication_port:<port>] - replication_port state=present"
  ini_file: dest="{{ splunk_conf_path }}/server.conf"
            section="replication_port://{{ splunk_server_conf.replication_port.port }}"
            state=present
<<<<<<< HEAD
=======
# This is a hack, workaround for bug in ini_file module
>>>>>>> f34390efdc5e0508cccf06576080bb89d9befafd
            option=dummy
  when: splunk_server_conf.replication_port.port is defined
  notify: splunk restart

- name: "Configure server.conf [replication_port:<port>] - replication_port check presence"
  shell: grep 'replication_port:' {{ splunk_conf_path }}/server.conf | sed 's/\[replication_port:\/\/\(.*\)]/\1/'
  register: splunk_server_replication_port_port_inifile
  changed_when: false
  notify: splunk restart

- name: "Configure server.conf [replication_port:<port>] - replication_port state=absent (default)"
  ini_file: dest="{{ splunk_conf_path }}/server.conf"
            section="replication_port://{{ splunk_server_replication_port_port_inifile.stdout }}"
            state=absent
  when: splunk_server_conf.replication_port.port is undefined and
        splunk_server_replication_port_port_inifile.stdout != ""
  notify: splunk restart
