---
# configuration for Splunk distsearch.conf
#
# indexcluster

- name: "Configure distsearch.conf [distributedSearch] - indexcluster state=present"
  ini_file: dest={{ splunk_conf_path }}/distsearch.conf
            section="distributedSearch:dmc_indexerclustergroup_{{ osu_environment }}"
            option=servers
            value="{{ groups['cluster'] | create_distsearch_servers }}"
            state=present
  when: groups['cluster'] is defined
  notify: splunk restart

- name: "Configure distsearch.conf [distributedSearch] - indexcluster state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/distsearch.conf
            section="distributedSearch:dmc_indexerclustergroup_{{ osu_environment }}"
            option=servers
            state=absent
  when: groups['cluster'] is undefined
  notify: splunk restart
