---
# Configuration for Splunk distsearch.conf
#
# searchhead

- name: "Configure distsearch.conf searchhead [distributedSearch] - searchhead state=present"
  ini_file: dest={{ splunk_conf_path }}/distsearch.conf
            section="distributedSearch:dmc_group_search_head"
            option=servers
            value="{{ groups['searchhead'] | create_distsearch_servers }}"
            state=present
  when: groups['searchhead'] is defined
  notify: splunk restart

- name: "Configure distsearch.conf searchhead [distributedSearch] - searchhead state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/distsearch.conf
            section="distributedSearch:dmc_group_search_head"
            option=servers
            state=absent
  when: groups['searchhead'] is undefined
  notify: splunk restart
