---
#####################################################################################################################
# Configurations for Splunk distsearch.conf
#####################################################################################################################

#####################################################################################################################
# [distributedSearch]
#####################################################################################################################

# server

- name: "Configure distsearch.conf [distributedSearch] - server state=present"
  ini_file: dest={{ splunk_conf_path }}/distsearch.conf
            section=distributedSearch
            option=servers
            value="{{ groups['shcmember']['deploymentserver']['licensemaster']['masternode'] | create_distsearch_servers  }}"
            state=present
  when: splunk_distsearch_conf.distributedSearch.servers is defined
  notify: splunk restart

- name: "Configure distsearch.conf [distributedSearch] - server state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/distsearch.conf
            section=distributedSearch
            option=servers
            state=absent
  when: splunk_distsearch_conf.distributedSearch.servers is undefined
  notify: splunk restart
