---
# Configuration for Splunk distserach.conf
#
# shcmember

- name: "Configure distsearch.conf [distributedSearch] - shcmember state=present"
  ini_file: dest={{ splunk_conf_path }}/distsearch.conf
            section="distributedSearch:dmc_searchheadclustergroup_{{ osu_environment }}"
            option=servers
            value="{{ groups['shcmember'] | create_distsearch_servers }}"
            state=present
  when: groups['shcmember'] is defined
  notify: splunk restart

- name: "Configure distsearch.conf [distributedSearch] - shcmember state=absent (default)"
  ini_file: dest={{ splunk_conf_path }}/distsearch.conf
            section="distributedSearch:dmc_searchheadclustergroup_{{ osu_environment }}"
            option=servers
            state=absent
  when: groups['shcmember'] is undefined
  notify: splunk restart
