---
- include: copy_addon.yml

- include: cleanup_deployer.yml
  when: "'deployer' in group_names"

- include: cleanup_masternode.yml
  when: "'masternode' in group_names"

- include: shcluster_push.yml
  when: "'deployer' in group_names"

- include: cluster_push.yml
  when: "'masternode' in group_names"
