---
- include: touch.yml
- include: "{{ item }}"
  when: splunk_server_conf.clustering is defined
  with_items:
    - clustering/pass4SymmKey.yml
    - clustering/available_sites.yml
    - clustering/cluster_label.yml
    - clustering/master_uri.yml
    - clustering/mode.yml
    - clustering/multisite.yml
    - clustering/replication_factor.yml
    - clustering/search_factor.yml
    - clustering/site_replication_factor.yml
- include: diskUsage/minFreeSpace.yml
  when: splunk_server_conf.diskUsage is defined
- include: general/pass4SymmKey.yml
- include: general/site.yml
- include: general/trustedIP.yml
- include: license/master_uri.yml
- include: replication_port/port.yml
  when: splunk_server_conf.replication_port is defined
- include: "{{ item }}"
  when: splunk_server_conf.replication_port_ssl is defined
  with_items:
    - replication_port-ssl/port.yml
    - replication_port-ssl/rootCA.yml
    - replication_port-ssl/serverCert.yml
    - replication_port-ssl/password.yml
- include: "{{ item }}"
  when: splunk_server_conf.shclustering is defined
  with_items:
    - shclustering/conf_deploy_fetch_url.yml
    - shclustering/conf_replication_include.yml
    - shclustering/enable.yml
    - shclustering/election.yml
    - shclustering/id.yml
    - shclustering/mgmt_uri.yml
    - shclustering/pass4SymmKey.yml
    - shclustering/replication_factor.yml
    - shclustering/shcluster_label.yml
- include: sslConfig/sslKeysfilePassword.yml
