---
- include: splunktcp/port.yml
  when: splunk_inputs_conf.splunktcp is defined
- include: splunktcp-ssl/port.yml
  when: "splunk_inputs_conf.splunktcpssl is defined"
- include: "{{ item }}"
  when: splunk_inputs_conf.SSL is defined
  with_items:
    - SSL/password.yml
    - SSL/rootCA.yml
    - SSL/serverCert.yml
