---
#####################################################################################################################
# Configurations for Splunk authentication.conf
#####################################################################################################################

# touch

- name: "Touch authentication.conf"
  file: path={{ splunk_conf_path }}/authentication.conf
        owner=splunk
        group=splunk
        mode=0600
        state=touch
  changed_when: false
