---
- name: Remove samples from deployer
  file: path="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/Splunk_TA_cisco-asa/samples"
        state=absent

- name: Remove eventgen.conf from deployer
  file: path="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/Splunk_TA_cisco-asa/default/eventgen.conf"
        state=absent

- name: Remove eventgen.conf from deployer
  file: path="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/Splunk_TA_cisco-asa/default/inputs.conf"
        state=absent
  notify: shcluster bundle push
