---
#####################################################################################################################
# Configurations for Splunk alert_actions.conf
#####################################################################################################################

# touch

- name: "Touch alert_actions.conf"
  file: path={{ splunk_conf_path }}/alert_actions.conf
        owner=splunk
        group=splunk
        mode=600
        state=touch
  changed_when: false
