---
#####################################################################################################################
# Copy Enterprise License Keys
#####################################################################################################################

- name: Create licenses/enterprise directory
  file: path="{{ splunk_installation.splunk_home_path }}/etc/licenses/enterprise"
        state=directory
        mode=700
        owner=splunk
        group=splunk

- name: Copy Enterprise License Keys to Licensemaster
  copy: src="{{ splunk_repository.repository_root }}/licenses/enterprise/Splunk.License.lic"
        dest="{{ splunk_installation.splunk_home_path }}/etc/licenses/enterprise"
        owner=splunk
        group=splunk
        mode=600
        backup=yes
  tags: copy_license
