---
#####################################################################################################################
# Copy Enterprise License Keys
#####################################################################################################################

- name: Create licenses/enterprise directory
  file: path="{{ splunk_installation.splunk_home_path }}/etc/licenses/enterprise"
        state=directory
        mode=0700
        owner=splunk
        group=splunk
  register: splunk_create_license_dir

- name: Copy Enterprise License Keys to Licensemaster
  local_action: "shell scp -r {{ splunk_repository.repository_root }}/licenses/enterprise/* splunk@{{ inventory_hostname }}:{{ splunk_installation.splunk_home_path }}/etc/licenses/enterprise"
  when: splunk_create_license_dir|succeeded or splunk_create_license_dir|skipped
