---
#####################################################################################################################
# Configurations for Splunk inputs.conf
#####################################################################################################################

#####################################################################################################################
# [splunktcp-ssl:<port>]
#####################################################################################################################

- name: "Configure inputs.conf [splunktcp-ssl:<port>] - splunktcpssl state=present"
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=splunktcpssl:{{ splunk_inputs_conf.splunktcpssl.port }}
            state=present
            option=dummy
  when: splunk_inputs_conf.splunktcpssl.port is defined
  notify: splunk restart

- name: "Configure inputs.conf [splunktcp-ssl:<port>] - splunktcpssl state=absent (default)"
  replace: dest="{{ splunk_conf_path }}/inputs.conf"
           regexp='\[splunktcpssl:\d+\]\n'
           replace=''
  when: splunk_inputs_conf.splunktcpssl.port is undefined
  notify: splunk restart
