---
- include: touch.yml
- include: settings/rproxy.yml
- include: settings/serverCert.yml
- include: settings/enableSplunkWebSSL.yml
- include: settings/httpport.yml
- include: settings/privKeyPath.yml
- include: settings/startwebserver.yml
- include: settings/updateCheckerBaseURL.yml

