---
- name: Remove samples from deployer
  file: path="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/Splunk_TA_ipfix/samples"
        state=absent

- name: Remove eventgen.conf from deployer
  file: path="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/Splunk_TA_ipfix/default/eventgen.conf"
        state=absent
