---

- name: Remove existing init.d script
  file: path=/etc/init.d/splunk
        state=absent

- name: Enable Splunk boot-start
  command: "{{ splunk_installation.splunk_home_path }}/bin/splunk enable boot-start -user splunk --answer-yes --accept-license"
  when: splunk_file_copy_complete|succeeded or splunk_file_copy_complete|skipped
