---

- name: Configure app files (local/*.conf)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/apps/{{ app_name }}/local/"
  when: vars['app_name'].apps is defined
  with_fileglob:
    - apps/local/*.conf

- name: Configure deployment-app files (local/*.conf)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/deployment-apps/{{ app_name }}/local/"
  when: vars['app_name'].deployment_apps is defined
  with_fileglob:
    - deployment-apps/local/*.conf

- name: Configure shcluster/apps files (local/*.conf)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/{{ app_name }}/local/"
  when: vars['app_name'].shcluster_apps is defined
  with_fileglob:
    - shcluster/apps/local/*.conf

- name: Configure master-apps files (local/*.conf)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/master-apps/{{ app_name }}/local/"
  when: vars['app_name'].master_apps is defined
  with_fileglob:
    - master-apps/local/*.conf

- name: Configure app permission file (metadata/local.meta)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/apps/{{ app_name }}/metadata/"
  when: vars['app_name'].apps is defined
  with_file:
    - apps/metadata/local.meta

- name: Configure deployment-app permission file (metadata/local.meta)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/deployment-apps/{{ app_name }}/metadata/"
  when: vars['app_name'].deployment_apps is defined
  with_file:
    - deployment-apps/metadata/local.meta

- name: Configure shcluster/apps permission file (metadata/local.meta)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/{{ app_name }}/metadata/"
  when: vars['app_name'].shcluster_apps is defined"
  with_file:
    - shcluster/apps/metadata/local.meta

- name: Configure master-apps permission file (metadata/local.meta)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/master-apps/{{ app_name }}/metadata/"
  when: vars['app_name'].master_apps is defined"
  with_file:
    - master-apps/metadata/local.meta

